<div class="photo-big-s">
        <div class="photo-pic"> <a href="[field:arcurl/]" title="<strong>[field:title/]</strong>" target="_blank"> <img src="[field:litpic/]" width="280" height="187" alt="<strong>[field:title/]</strong>"></a> </div>
        <h3><a href="[field:arcurl/]" title="<strong>[field:title/]</strong>" target="_blank"><strong>[field:title/]</strong></a></h3>
        <div class="meta"> <span class="meta-column"><i></i> <a href="[field:typeurl/]" title="[field:typename/]" target="_blank">[field:typename/]</a></span> <span class="delim"></span> <span class="meta-data">[field:pubdate function="MyDate('Y年m月d日',@me)"/]</span> <span class="delim"></span> <span class="meta-column"><i></i>点击：[field:click/] </span> </div>
      </div>