<li>
                      <div class="img-con"> <a href="[field:arcurl/]" target="_blank" title="[field:fulltitle/]"> <img src="[field:picname/]" width="600" height="336" alt="[field:fulltitle/]"></a> </div>
                      <div class="txt">
                        <div class="cl">
                          <div class="caption_info"> <span class="num">0[field:global runphp='yes' name=autoindex]</span> <span class="author">围观：[field:click/]</span> <span class="data">[field:pubdate function="MyDate('Y年m月d日',@me)"/]</span> </div>
                          <h2><a href="[field:arcurl/]" target="_blank" title="[field:fulltitle/]">[field:title/]</a></h2>
                        </div>
                        <p>[field:infos/]</p>
                        <a href="[field:arcurl/]" target="_blank" title="[field:fulltitle/]" class="read-more">Read More &#187;</a> </div>
                    </li>