<li class="photo-big">
<div class="photo-pic"> 
<a href="[field:arcurl/]" target="_blank">
<img src="[field:litpic/]" alt="[field:title/]"></a> 
<a href="[field:arcurl/]" target="_blank" title="[field:title/]" class="mask"></a> </div>
<h3><a href="[field:arcurl/]" class="link" target="_blank"><b>[field:title/]</b></a> </h3>
<div class="meta"> 
<span class="meta-column"><i></i>
TAG：[field:id function=GetTags(@me)/]</span> <span class="delim"></span>
<span class="meta-data">[field:pubdate function="MyDate('Y年m月d日',@me)"/]</span> 
</div>
<p>[field:infos/]... </p>
</li>