<div class="photo-big mr30">
          <div class="photo-pic"> <a href="[field:arcurl/]" title="[field:fulltitle/]" target="_blank"> <img src="[field:litpic/]" width="330" height="220" alt="[field:fulltitle/]"></a> </div>
          <h3><a href="[field:arcurl/]" title="[field:fulltitle/]" target="_blank">[field:title/]</a></h3>
          <div class="meta"> <span class="meta-column"><i></i> <a href="[field:typeurl/]" title="[field:typename/]" target="_blank">[field:typename/]</a></span> <span class="delim"></span> <span class="meta-data">[field:pubdate function="MyDate('Y年m月d日',@me)"/]</span> <span class="delim"></span> <span class="meta-column"><i></i>查看：[field:click/]次 </span> </div>
          <p class="mt20">[field:infos/]……</p>
        </div>