<li>
<div class="wonderful-pic">
	<a href="[field:arcurl/]" title="[field:title/]" target="_blank"><i></i>
		<img src="[field:litpic/]" width="280" height="220" alt="[field:title/]"></a>
<div class="text-box">
<h3><a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></h3>
<div class="meta"> <span class="meta-column"><i></i>
	<a href="[field:typeurl/]" title="[field:typename/]" target="_blank">[field:typename/]</a></span>
</div>
</div>
</div>
</li>